TrainingLoop: refactor progress printer and add CSVLogger
tensorflow/swift-models pull request #668
Opened 2020-09-15 21:12 UTC by xihui-wu

This is the first step address of https://github.com/tensorflow/swift-models/issues/663. Highlights of the change:

1. Add StatisticsRecorder and ProgressPrinter as pre-registered callbacks to TrainingLoop. (as [fastai](https://github.com/fastai/fastai/blob/master/fastai/callback/progress.py#L55) does)
2. Add CSVLogger callback.

2020-09-16 16:50 UTC, BradLarson commented on TrainingLoop/TrainingLoop.swift
> +    ] + callbacks
I can imagine cases where we don't want to record per-batch or per-epoch statistics. By building statistics gathering directly into the training loop, rather than having it be a user-provided component, can we account for those cases where we want to strip down the training loop as much as possible?

2020-09-16 21:57 UTC, xihui-wu commented on TrainingLoop/TrainingLoop.swift
> +    ] + callbacks
Yes please see latest change where I make both whether to include default callbacks and when to record stats configurable.

2020-09-18 16:59 UTC, dabrahams requested changes
Reviewed the first file.  Please revise (and apply anything you learned from doing so to the other files) and I can look again.  Thanks!

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// Create an instance that log statistics during the training loop.
“during the training loop” is not true about this initializer, only about how you happen to use it later.  The doc comment should say something about how the parameters are used.

```suggestion
  /// Creates an instance that logs to a file with the given path.
```

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public init(withPath path: String = "run/log.csv") {
Almost never use "with" to introduce parameters.  It adds no information for the reader beyond what you'd get from `path`.  Of course you're calling this intializer “with” that path!

```suggestion
  public init(path: String = "run/log.csv") {
```

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    self.path = path
It seems very unlikely to me that we actually need to store `path` in addition to `foundationFile`.  Consider whether it can/should be dropped because you can get it from `foundationFile`.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    self.foundationFS = FoundationFileSystem()
Storing a copy of the filesystem seems suspect, just logically speaking.  Are these instances not really all the same thing (singleton)?  Should we just construct the instance on the fly when we need it?

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  let foundationFile: FoundationFile
Doc comment please. Don't name things after their types.

If you rename the thing `CSVLogFile` or something, then:

```suggestion
  let underlyingFile: FoundationFile
```

or

```suggestion
  let rawFile: FoundationFile
```

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// The callback used to hook into the TrainingLoop for logging statistics.
This is a function, so you say what it *does*, per 

> Describe what a function or method does and what it returns, omitting null effects and Void returns

Please read https://swift.org/documentation/api-design-guidelines/#fundamentals

```suggestion
  /// Logs the end of an iteration of `loop`; ignoring other events.
```

or something.

Also, please describe the conditions under which it might throw.  It is probably enough to say that filesystem errors are reported by throwing.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// - Parameters:
You almost certainly don't need a parameters block because you can describe the parameters in the summary.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public func log<L: TrainingLoopProtocol>(_ loop: inout L, event: TrainingLoopEvent) throws {
Both parameters are named after their types.  You might not be able to find a better name for `event` (but you might! “`occurrence`” probably isn't an improvement).  “`loop`” surely could be `session` or something… though maybe we should be using `Session` as part of the type and protocol names.  Anyway, it's worth doing some work on this.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        return
Why would any of these things be `nil`, and why are we bailing out when they're `nil`?  That should be explained in a comment.  Ditto for `stats` below.  Also, why are these two separate guard statements?

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      if !FileManager.default.fileExists(atPath: path) {
I would do this upon creation of the logger, holding the file open for write, rather than checking the filesystem each time anything is logged.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
It took me a while to figure out what was happening here, but IIUC this will do the wrong thing if the path you were passed happens to end with "/".

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
The fact that you append to a log file that already exists rather than overwriting it needs to be in a doc comment somewhere.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
The fact that you try to create the containing directory if it is missing needs to be in a doc comment somewhere.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      try writeDataRow(
Could probably be 1 line?

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      print("Unexpected error in writing header line: \(error).")
This is the worst of both worlds: while forcing clients to deal with a thrown error, it gives them no choice about whether the error is reported.  Either:

1. consider the error thrown by `write` to be informative enough and simply skip the `do… catch`, or
2. Create your own error (`CSVLogger.HeaderWriteError`) that wraps the thrown error, and throw that instead from the Catch block.

my instinct says #1 is the answer.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
`.0` is indexing a tuple, but I assume it's a statistic name.  It would be better if the fields of the tuple were labeled and you could use the label (`$0.name`).  If you have control over that, consider making the change.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
```suggestion
    let head: String = (["epoch", "batch"] + stats.lazy.map { $0.0 }).joined(separator: ", ")
```

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
This is another example where the let binding "`head`" is providing dubious value.  The name is not great if you're going to use a let binding; it isn't “a head.” Otherwise,
```suggestion
    (["epoch", "batch"] + stats.lazy.map { $0.0 }).joined(separator: ", ")
      .write(toFile: path, atomically: true, encoding: .utf8)
```

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      print("Unexpected error in writing header line: \(error).")
Same remarks apply to `writeDataRow`.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let dataRow: Data = (
Why are we creating `Data` from a `String` here?  Surely `foundationFile` can append a string?

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      "\n" + ([epoch, batch] + stats.map { String($0.1) }).joined(separator: ", ")
It's traditional good form that files end with `"\n"`, so I would write this at the end of the header and at the end of each line you write.

2020-09-18 16:59 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      try foundationFile.append(dataRow)
Isn't it important to do this atomically if there are multiple writers to the same log file?

2020-09-22 05:02 UTC, xihui-wu commented on Examples/LeNet-MNIST/main.swift
> +(trainingLoop.statisticsRecorder!).shouldCompute = {
Done.

2020-09-22 05:04 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +/// A callback-based handler for logging the statistics to CSV file.
Updated the doc comment. Any reason why this is LogFile? (Logger makes sense to me since its a logger not a file)

2020-09-22 05:05 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public var path: String
Done

2020-09-22 05:06 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  let foundationFS: FoundationFileSystem
Removed the FoundationFileSystem instance and create on the fly.

2020-09-22 05:08 UTC, xihui-wu commented on Support/FoundationFileSystem.swift
> +  public func append(_ value: Data) throws {
Done.

2020-09-22 05:08 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// Create an instance that log statistics during the training loop.
Done.

2020-09-22 05:09 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    self.path = path
Same. Removed foundationFile and kept the path.

2020-09-22 05:10 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  let foundationFile: FoundationFile
Removed foundationFile.

2020-09-22 05:10 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// - Parameters:
Good to know. Done.

2020-09-22 05:14 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        return
Merged stats into the same guard statements.
These are designed as optionals in existing TrainingLoop. I think that's because it's not the must-have values to complete a training process. I added an inline comment.

2020-09-22 05:15 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
Oh yes I omitted this case.

2020-09-22 05:17 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
done.

2020-09-22 05:17 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      print("Unexpected error in writing header line: \(error).")
got it.

2020-09-22 05:18 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
Good suggestion. Done.

2020-09-22 05:19 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
Does lazy have much impact in the performance in this case ?

2020-09-22 05:20 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
How about header ?

2020-09-22 05:21 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let dataRow: Data = (
Not it can't. It appears to me that we have designed the FoundationFile to handle operations on Data only.

2020-09-22 05:21 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      "\n" + ([epoch, batch] + stats.map { String($0.1) }).joined(separator: ", ")
Got it.

2020-09-22 05:31 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public init(withPath path: String = "run/log.csv") {
Done.

2020-09-22 05:32 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    self.foundationFS = FoundationFileSystem()
Yeah good to create on the fly

2020-09-22 05:35 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// The callback used to hook into the TrainingLoop for logging statistics.
Done.

2020-09-22 05:38 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public func log<L: TrainingLoopProtocol>(_ loop: inout L, event: TrainingLoopEvent) throws {
I assume "trainingLoopEvent" is named after their types but "event" is not. Is there a strict rule for this? 
To me "event" is much more straightforward than "occurrence" tho.

2020-09-22 05:38 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      if !FileManager.default.fileExists(atPath: path) {
Got it.

2020-09-22 05:39 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        try foundationFS.createDirectoryIfMissing(at: String(path[..<path.lastIndex(of: "/")!]))
I'd rather to overwrite it actually. Added comment inside the new init.

2020-09-22 05:40 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      try writeDataRow(
This is outdated. Moved createDirectoryIfMissing to init.

2020-09-22 16:16 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      try foundationFile.append(dataRow)
Does FileHandle support atomically write ? (Also, we won't expect multiple files written at same time I think)

2020-09-22 16:46 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public func log<L: TrainingLoopProtocol>(_ loop: inout L, event: TrainingLoopEvent) throws {
There's no strict rule.

Consider:

```
let arrayInt = students.map(\.grade) // definitely named after the type, I'm sure you agree
let array = students.map(\.grade)    // still named after type, just less specific
let grades = students.map(\.grade)   // named after role/meaning
```

`event` is like `array` above.  I agree "event" is better than "occurrence," (not more than a long synonym for “event”) which is why I said “occurrence” is probably not an improvement.   The type and name of a parameter name both make a statement about that parameter. If you just use words from the type in the parameter name one often gives up an opportunity to make a more meaningful statement with the parameter name.  I'm not saying that's the case here with `event`; sometimes there is no way to do better than repeating type information.  I'm saying, **notice** that the name contains only type information and  **take a few moments** to see if you can do better.  That's all.  If you don't come up with anything, that's fine; just move on.

2020-09-22 17:11 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        return
OK, first, I would rather see something like 

```
// These properties will be `nil` unless stats logging was requested
```
because it describes the situation at a semantic level rather than at the level of what some code did.

(also writing "No-Op" adds nothing to what is already very obvious from the code)

But that said, it seems very unlikely that the comment I'd like to see is true of any but the last property.  All the others refer to values that have nothing to do with logging.  So I want to know what causes `epochIndex` to be `nil`, for example.

It's a big design flaw in trainingLoop that it has so many optionals, and that makes this task more difficult, but I believe that's not the code you're working on(?)

2020-09-22 17:55 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  // The boolean variable indicating if header of the CSV file has been written or not.
```suggestion
  // True iff the header of the CSV file has been written.
```

Everyone can see it's a `Bool`.  The phrasing “indicating if … or not” is not clear about the polarity of the `Bool`.

2020-09-22 17:57 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    self.path = path
Hmm, I'm not sure you want to open and close the file for every line logged, though.  (I am presuming that  the `foundationFile` object keeps the file open)

2020-09-22 18:00 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    if containingDir != "" {
why would this string ever be empty?  I don't think it would.  Why add a check for it?

2020-09-22 18:02 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      if !headerWritten {
Why track this value rather than simply writing the header when the `Logger` is initialized?

2020-09-22 18:04 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let header: String = (["epoch", "batch"] + stats.map { $0.name }).joined(separator: ", ") + "\n"
```suggestion
    let header: String = (["epoch", "batch"] + stats.lazy.map { $0.name }).joined(separator: ", ") + "\n"
```

Didn't I already make this suggestion?

2020-09-22 19:19 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    if containingDir != "" {
If the path is sth like "/log.csv" then containingDir is empty.
Thought twice and I just changed to use URL to handle the parsing.

2020-09-22 19:20 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +      if !headerWritten {
I need to figure out what header to write from the stats names.

2020-09-22 19:24 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  // The boolean variable indicating if header of the CSV file has been written or not.
Got it!

2020-09-22 19:33 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public func log<L: TrainingLoopProtocol>(_ loop: inout L, event: TrainingLoopEvent) throws {
Got it. The TrainingLoopCallback was designed with these parameters https://github.com/tensorflow/swift-models/blob/master/TrainingLoop/TrainingLoop.swift#L129 and I took what already there. 

I could understand from your example that when the type is very generic, naming after role/meaning is important, but when the type is relatively specific then it's harder to pick a better meaningful name. Yeah if you can't think of a better name, let me keep "event".

2020-09-22 19:43 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +        return
These variables were originally designed to be optionals to store temporary data in protocol: https://github.com/tensorflow/swift-models/blob/master/TrainingLoop/TrainingLoop.swift#L76

The generic TrainingLoop that implements the protocol does set all these optionals. My guess on why it was designed so is that it allows other TrainingLoops not setting them.

So the point on the comment is NOT "if stats logging doesn't request it then these properties will be nil", but "if these properties are nil No-op on the CSVLogger".

2020-09-23 17:00 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let header: String = (["epoch", "batch"] + stats.map { $0.name }).joined(separator: ", ") + "\n"
Got it.

2020-09-23 22:28 UTC, dabrahams requested changes

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/Metrics.swift
> +/// A protocal defining functionalities of a metrics measurer.
That doc comment doesn't tell me anything that isn't obvious from the following line of code.  Never start a protocol's doc summary with "A protocol".  I have to admit that I'm still searching for an non-awkward way to describe protocols; recently I have settled on “Types that…” because a protocol represents a category of types, e.g., "Types that accumulate statistics from a series of `Tensor<Float>`-valued samples,”  (or something) but you could also just say ”An accumulator of statistics.”

Is this, conceptually, like what's described here?  https://www.boost.org/doc/libs/1_74_0/doc/html/accumulators.html
If so, I suggest borrowing naming and documentation language choices from that library (I was one of the library's designers).

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/Metrics.swift
> +  var name: String { get set }
doc comments are required on all methods and properties.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/Metrics.swift
> +  public var name: String
Doc comments are required on all methods and properties of this type.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/Metrics.swift
> +  public var name: String
Doc comments are required on all methods and properties of this type.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/Metrics.swift
> +    guard let predictions = predictions as? Tensor<Float>, let labels = labels as? Tensor<Int32>
This is an unfortunately late point at which to detect the type mismatch.  Ideally it would be done at compile-time.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  public typealias F = @differentiable(Output, @noDerivative Target) -> Tensor<Float>
```suggestion
  public typealias F = @differentiable (Output, @noDerivative Target) -> Tensor<Float>
```

I don't _think_ we'd normally drop that space.  Regardless, it's a good idea to avoid making needless whitespace changes on lines you don't otherwise have to edit.  If you want to do a whitespace cleanup commit, it should usually be a separate PR.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  /// The metrics
Do better, e.g.,

```suggestion
  /// The statistics being tracked.
```

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  var lastStepInput: Input? { get set }
When you see repetition like this, the instinct should be to replace it with something like:

```swift
var lastStep: Step?
```

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  var epochCount: Int? { get set }
Why are these optional?  Usually, 2-phase initialization indicates a design error.

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  /// The log for last statistics
last what?  We have last epoch, last step, …

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  /// The metrics
Do better please

2020-09-23 22:28 UTC, dabrahams commented on TrainingLoop/TrainingLoop.swift
> +  public var callbacks: [TrainingLoopCallback<Self>]
Doc comments missing.

2020-09-23 22:41 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +/// A callback-based handler for logging the statistics to CSV file.
This thing can only be constructed to log to a path in the filesystem, and when we invoke its one public method, `log`, it appends to that file.  Properly used, if you have multiple instances, each instance logs to a different file.  The word `Logger` doesn't imply any of those things.  A more general `Logger` might be an interesting abstraction, but it would have a different API.

If I see this code, I know exactly what's happening.  
```swift
// No argument label needed, arguably, because when you construct a thing called “File” with
// a string, the string is obviously a path.
LogFile log(s)

log.append(blah, blah, blah)
```
With `Logger` and `log`, it's less clear.

2020-09-23 23:48 UTC, xihui-wu commented on Support/FoundationFileSystem.swift
> +  /// Append data to the file.
Got it.

2020-09-23 23:48 UTC, xihui-wu commented on Support/FoundationFileSystem.swift
> +  /// Parameter value: data to be appended at the end.
Got it

2020-09-23 23:49 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  /// The path of the file that statistics are logged to.
Done

2020-09-23 23:58 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +  public func log<L: TrainingLoopProtocol>(_ loop: inout L, event: TrainingLoopEvent) throws {
Thanks for the clarification.

2020-09-23 23:58 UTC, xihui-wu commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let head: String = (["epoch", "batch"] + stats.map { $0.0 }).joined(separator: ", ")
Chatted offline and resolved

2020-09-24 00:19 UTC, dabrahams commented on TrainingLoop/Callbacks/CSVLogger.swift
> +    let dataRow: Data = (
Bleah!

2020-09-24 00:21 UTC, dabrahams approved these changes
Approving to unblock progress but there are lots of things to fix, including many that are simply mechanical (missing doc comments).

2020-09-24 00:34 UTC, xihui-wu commented
> Approving to unblock progress but there are lots of things to fix, including many that are simply mechanical (missing doc comments).

Thanks! Will come with new PRs to address:
1. @dabrahams's open comments
2. An easier interface for specifying when to compute stats (as per @BradLarson )
3. Potential changes in metrics / loss as I have new findings when converting GPT2 to TrainingLoop. (this is also what I'm blocked on and wanted to make iteration on top of this PR change)

2020-09-24 00:35 UTC, merged