Pix2 pix checkpoint
tensorflow/swift-models pull request #696
Opened 2020-11-02 23:54 UTC by inukshukdeveloper

This is draft PR that follows the checkpoint pattern established by other models (e.g. GPT2).  This work wasn't planned on being formally submitted but some of it may be useful depending on where S4TF is headed.  It only writes checkpoints for the generator half of the GAN but obviously could be extended to the discriminator as well.

There are some other utility odds and ends (e.g. extension to Image to conform to Equatable) that may be of interest.  

If any (or none) of the PR is suitable for inclusion, feedback is certainly welcome.

Several TODOs are also sprinkled throughout to show obvious remaining holes.

2020-11-04 15:24 UTC, BradLarson commented
It's unfortunate that I've been focused on other work and haven't been able to push [this PR](https://github.com/tensorflow/swift-models/pull/631) across the finish line, because that would remove a large portion of the boilerplate code here. You can see in that PR how the GPT-2 example is simplified, for example.

I haven't been pushing forward with other checkpoint-related extensions to models until that PR is completed, but I know it would be nice to have this available in many models here.

All that said, would you still like for us to continue to review the finer components of this PR?

2020-11-04 19:40 UTC, inukshukdeveloper commented
No problem.  I've been checking in on the progress of PR 631 and suspected
portions of this PR will be redundant once PR 631 appears.

Yes, if you feel other portions of this draft PR would be useful, please
take a look.  I welcome any feedback.

Cheers,
Mark

On Wed, Nov 4, 2020 at 7:24 AM Brad Larson <notifications@github.com> wrote:

> It's unfortunate that I've been focused on other work and haven't been
> able to push this PR <https://github.com/tensorflow/swift-models/pull/631>
> across the finish line, because that would remove a large portion of the
> boilerplate code here. You can see in that PR how the GPT-2 example is
> simplified, for example.
>
> I haven't been pushing forward with other checkpoint-related extensions to
> models until that PR is completed, but I know it would be nice to have this
> available in many models here.
>
> All that said, would you still like for us to continue to review the finer
> components of this PR?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/swift-models/pull/696#issuecomment-721797251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJRYIUV2XTWGEW3KNXQAUQ3SOFW4HANCNFSM4TICWWLQ>
> .
>

2020-11-18 23:34 UTC, inukshukdeveloper commented
Procedural question: should I mark this draft PR as ready to review or will it be reviewed in its draft state?

Thanks,
Mark

2020-11-19 18:00 UTC, inukshukdeveloper commented
Submitting for review.  It's understood a good portion of this PR is redundant pending completion of PR 631 but portions could be of use now.   Also, TODO items may be useful but would need feedback as to whether finishing them would be worthwhile.

2020-12-16 15:57 UTC, BradLarson commented on Package.swift
> -        .target(name: "Gym-DQN", path: "Gym/DQN"),
We probably don't want to remove this target, so this line should be reverted.

2020-12-16 16:01 UTC, BradLarson commented on Support/Image.swift
> +extension Image: Equatable {
Where do we need images to be Equatable? Comparing images has always been tricky, especially in unit tests, and images backed by floating-point tensors might have tiny differences due to conversions. This also performs an implicit conversion to floating-point values from UInt8-based images.

2020-12-16 16:02 UTC, BradLarson commented on pix2pix/CheckpointWriter.swift
> +
Minor formatting issue: there's a lot of whitespace at the end of the file here.

2020-12-16 16:03 UTC, BradLarson commented on pix2pix/Dataset.swift
> -
I think it's preferable to have the blank line here.

2020-12-16 16:05 UTC, BradLarson commented on pix2pix/Dataset.swift
> +            variant: variant ?? .maps,
Do we want to switch the default to the maps dataset? All of the instructions use the facades dataset as an example.

2020-12-16 16:06 UTC, BradLarson commented on pix2pix/Generator.swift
> +
Minor nit: swift-format would place `import TensorFlow` here, so that these are in alphabetical order.

2020-12-16 16:08 UTC, BradLarson commented on pix2pix/Generator.swift
> +        // TODO: Copy auxiliary files if they need to be in different location than current
I'd probably remove the commented-out code here, if it's currently nonfunctional. It can be added back in later.

2020-12-16 16:10 UTC, BradLarson commented on pix2pix/Layers.swift
> +*/
This can probably be removed.

2020-12-16 16:12 UTC, BradLarson commented on pix2pix/PythonCheckpointReader.swift
> +
This file will need a copyright header. My recommendation would be to also rename it `CheckpointReader.swift`, because there really isn't any Python involved in these anymore. I think I started to migrate over some of the legacy files that were named like this, but there might still be some stragglers.

2020-12-16 16:13 UTC, BradLarson commented on pix2pix/PythonCheckpointReader.swift
> +    associatedtype Sublayer: Layer where Sublayer.TangentVector.VectorSpaceScalar == Float, Sublayer.Input == Tensor<Float>, Sublayer.Output == Tensor<Float>
Some of these lines are getting a little long, so running swift-format against this file might help to wrap these.

2020-12-16 16:13 UTC, BradLarson commented on pix2pix/PythonCheckpointReader.swift
> +
Like with other commented code, I'd recommend removing this if it's nonfunctional and bringing it in later.

2020-12-16 16:14 UTC, BradLarson commented on pix2pix/PythonCheckpointReader.swift
> +
Minor formatting nit: there's a bunch of extra whitespace at the end of this file, as well.

2020-12-16 16:16 UTC, BradLarson commented on pix2pix/Generator.swift
> +extension NetG: Equatable {
As with Image, why do we need to conform this and the other layers below to Equatable? If we don't need that functionality, we could probably remove these conformances to simplify the code here.

2020-12-16 16:16 UTC, BradLarson commented on pix2pix/main.swift
> -
I think we'd prefer to have the line space here.

2020-12-16 16:17 UTC, BradLarson commented on pix2pix/main.swift
> +
Nit: there are a few odd whitespace insertions here and on lines 101 and 105.

2020-12-16 16:18 UTC, BradLarson commented on pix2pix/main.swift
> +
This seems left over from the GPT-2 example, and can be removed if it doesn't apply here.

2020-12-16 16:32 UTC, BradLarson requested changes
Thanks for working on this, and sorry for the late review.

There are a few merge conflicts that might need to be resolved to bring this in. I've also provided comments in several places for areas where I wasn't clear as to why we needed Equatable conformances, as well as a number of minor whitespace issues. For the nonfunctional code, I think it would probably be preferable to remove it for now and add it back in later once it is operational.

2020-12-18 19:16 UTC, inukshukdeveloper commented
Thanks for the review.  I'll begin looking at incorporating the feedback here shortly.

2021-02-02 20:24 UTC, inukshukdeveloper commented on Package.swift
> -        .target(name: "Gym-DQN", path: "Gym/DQN"),
Reverted.

2021-02-02 20:28 UTC, inukshukdeveloper commented on Support/Image.swift
> +extension Image: Equatable {
I used this to validate that the restored generator from the checkpoint was producing identical images to a freshly trained generator.  I thought it might be useful to others but if there are floating point comparison issues, then I will gladly remove it.  Is there another method to validate image output?

2021-02-02 20:29 UTC, inukshukdeveloper commented on pix2pix/CheckpointWriter.swift
> +
Cleaned up the formatting.

2021-02-02 20:29 UTC, inukshukdeveloper commented on pix2pix/Dataset.swift
> -
Removed blank line.

2021-02-02 20:31 UTC, inukshukdeveloper commented on pix2pix/Dataset.swift
> +            variant: variant ?? .maps,
Well spotted.  Nope, didn't want to make it the default.  Reverted default back to facades.

2021-02-02 20:35 UTC, inukshukdeveloper commented on pix2pix/Generator.swift
> +
Moved TensorFlow import statement down to its alphabetical location.

2021-02-02 20:39 UTC, inukshukdeveloper commented on pix2pix/Generator.swift
> +        // TODO: Copy auxiliary files if they need to be in different location than current
Removed the commented-out code but left a TODO regarding auxiliary files.  Not sure what the accepted practice is regarding TODOs but I saw a few sprinkled throughout the code base so went ahead and left it in.

2021-02-02 20:42 UTC, inukshukdeveloper commented on pix2pix/Generator.swift
> +extension NetG: Equatable {
Similar to image, I used the Equatable protocol to validate that the restored GAN was identical to the freshly trained GAN.  No worries.  Removed.

2021-02-02 21:00 UTC, inukshukdeveloper commented on pix2pix/Layers.swift
> +*/
Removed.

2021-02-02 21:01 UTC, inukshukdeveloper commented on pix2pix/PythonCheckpointReader.swift
> +
Added copyright and renamed to CheckpointReader.swift.

2021-02-02 21:03 UTC, inukshukdeveloper commented on pix2pix/PythonCheckpointReader.swift
> +
Removed.

2021-02-02 21:04 UTC, inukshukdeveloper commented on pix2pix/PythonCheckpointReader.swift
> +
Cleaned up whitespace.

2021-02-02 21:04 UTC, inukshukdeveloper commented on pix2pix/main.swift
> -
Added blank line.

2021-02-02 21:11 UTC, inukshukdeveloper commented on pix2pix/main.swift
> +
I deleted some of the white space but could use feedback on blank line style convention.  I occasionally add a blank line to separate a block if it's performing some logically connected work but am open to any other conventions.

2021-02-02 21:11 UTC, inukshukdeveloper commented on pix2pix/main.swift
> +
Removed.

2021-02-02 23:05 UTC, inukshukdeveloper commented on pix2pix/PythonCheckpointReader.swift
> +    associatedtype Sublayer: Layer where Sublayer.TangentVector.VectorSpaceScalar == Float, Sublayer.Input == Tensor<Float>, Sublayer.Output == Tensor<Float>
I ran swift-format on this file but didn't see much improvement, in my opinion.  I used the default configuration.  Is there possible a JSON with local conventions to S4TF?

2021-02-03 19:14 UTC, inukshukdeveloper reviewed
Sincere apologies for the delay in incorporating the comments from the review.  I got distracted reading Rahul's new book :) 

In all seriousness, I appreciate the feedback.  I see more checkpoint functionality has appeared since the first submission so this work may be more obsolete.  I did, however, fix a bug with file formatting assumptions in the pix2pix dataset.  I incorporated it into this work.

2021-02-16 15:32 UTC, BradLarson commented
We'd like to get our last pull requests in within the next couple of days, in order to cleanly archive swift-models. Is there a way to re-scope this in time to use the new checkpointing API and simply incorporate your fixes? If so, we could bring that in before archiving.

I totally understand if that would take too much time, given the short notice we've provided. If it can't be done in time, I still appreciate the effort that you put in to enhance this.

2021-02-16 20:57 UTC, inukshukdeveloper commented
I can give it a shot.  Checkpointable went onto main just recently, right?

-Mark

On Tue, Feb 16, 2021 at 7:32 AM Brad Larson <notifications@github.com>
wrote:

> We'd like to get our last pull requests in within the next couple of days,
> in order to cleanly archive swift-models. Is there a way to re-scope this
> in time to use the new checkpointing API and simply incorporate your fixes?
> If so, we could bring that in before archiving.
>
> I totally understand if that would take too much time, given the short
> notice we've provided. If it can't be done in time, I still appreciate the
> effort that you put in to enhance this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/swift-models/pull/696#issuecomment-779914282>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJRYIUX7DGGDA4KAFJYA3GDS7KFZTANCNFSM4TICWWLQ>
> .
>

2021-02-17 20:56 UTC, inukshukdeveloper commented
Hey Brad, 

I just tried a model checkpoint write/read round trip and got a fatal error where the number of key paths does not equal the number of tensor names (58 vs 84 in my case).  I simply wrote the checkpoint and read it back in without any customization.  I haven't started digging into it yet but I thought I'd see if there is something obvious I'm missing.

-Mark

2021-02-17 22:14 UTC, brettkoonce commented
@inukshukdeveloper you might look at some of the notes in #733

2021-02-17 23:49 UTC, inukshukdeveloper commented
@brettkoonce Thanks!  Working much better now.

2021-02-26 19:23 UTC, inukshukdeveloper commented
Looks like GPT2 tests are failing to initialize when trying to read the checkpoint index file.  The location appears to be the same in the branch and main (https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.index) but the load is failing.  Did I miss something in the merge?

2021-03-01 19:04 UTC, BradLarson approved these changes
Looking into it, I think the test failures are due to GPT-2's checkpoint being removed from its bucket. We'll see if there's an alternative, but that doesn't impact this PR.

Sorry for the delay in reviewing this, was out for a little while. Glad to have this in, thanks.

2021-03-01 19:05 UTC, merged